export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_NOW_SHOWING_MOVIES = 'FETCH_NOW_SHOWING_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';

export const FETCH_NEWS = 'FETCH_NEWS';
export const CLEAR_NEWS = 'CLEAR_NEWS';

export const FETCH_TWEETS = 'FETCH_TWEETS';
export const CLEAR_TWEETS = 'CLEAR_TWEETS';
