export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_NOW_PLAYING_MOVIES = 'FETCH_NOW_PLAYING_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';
