export enum MoviesAction {
  FETCH_MOVIES = 'FETCH_MOVIES',
  FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES',
  FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES',
  FETCH_NOW_SHOWING_MOVIES = 'FETCH_NOW_SHOWING_MOVIES',
  FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES',
  FETCH_MOVIE = 'FETCH_MOVIE',
  CLEAR_MOVIES = 'CLEAR_MOVIES',
  SET_CONTROL = 'SET_CONTROL'
}
export enum NewsAction {
  FETCH_NEWS = 'FETCH_NEWS',
  CLEAR_NEWS = 'CLEAR_NEWS'
}

export enum TweetsAction {
  FETCH_TWEETS = 'FETCH_TWEETS',
  CLEAR_TWEETS = 'CLEAR_TWEETS'
}
